services:
  mysql:
    image: mysql:8.0
    container_name: elderconnect-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: elderconnect
    ports:
      - "3307:3306"
    volumes:
      - elderconnect_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  elderconnect_data:
